export enum Layer {
    CANOPY = "CANOPY",
    SUBCANOPY = "SUBCANOPY",
    SHRUB = "SHRUB",
    HERBACEOUS = "HERBACEOUS",
    GROUNDCOVER = "GROUNDCOVER",
    ROOT = "ROOT",
    VINE = "VINE",
    WATER = "WATER",
    FUNGAL = "FUNGAL"
}
